# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 550)
        MainWindow.setMinimumSize(QtCore.QSize(500, 550))
        MainWindow.setMaximumSize(QtCore.QSize(500, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gameFieldTableView = QtWidgets.QTableView(self.centralwidget)
        self.gameFieldTableView.setEnabled(True)
        self.gameFieldTableView.setGeometry(QtCore.QRect(50, 100, 402, 402))
        self.gameFieldTableView.setFont(QtGui.QFont("Times", 24, QtGui.QFont.Bold))
        self.gameFieldTableView.setObjectName("gameFieldTableView")
        self.gameFieldTableView.horizontalHeader().setVisible(False)
        self.gameFieldTableView.horizontalHeader().setDefaultSectionSize(100)
        self.gameFieldTableView.horizontalHeader().setMinimumSectionSize(100)
        self.gameFieldTableView.verticalHeader().setVisible(False)
        self.gameFieldTableView.verticalHeader().setDefaultSectionSize(100)
        self.gameFieldTableView.verticalHeader().setMinimumSectionSize(100)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(370, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.strScore = QtWidgets.QLabel(self.centralwidget)
        self.strScore.setGeometry(QtCore.QRect(190, 50, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.strScore.setFont(font)
        self.strScore.setObjectName("strScore")
        self.strTheBestScore = QtWidgets.QLabel(self.centralwidget)
        self.strTheBestScore.setGeometry(QtCore.QRect(280, 50, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.strTheBestScore.setFont(font)
        self.strTheBestScore.setObjectName("strTheBestScore")
        self.valueTheBestScore = QtWidgets.QLabel(self.centralwidget)
        self.valueTheBestScore.setGeometry(QtCore.QRect(280, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.valueTheBestScore.setFont(font)
        self.valueTheBestScore.setObjectName("valueTheBestScore")
        self.str2048 = QtWidgets.QLabel(self.centralwidget)
        self.str2048.setGeometry(QtCore.QRect(50, 40, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.str2048.setFont(font)
        self.str2048.setObjectName("str2048")
        self.valueScore = QtWidgets.QLabel(self.centralwidget)
        self.valueScore.setGeometry(QtCore.QRect(190, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.valueScore.setFont(font)
        self.valueScore.setObjectName("valueScore")
        self.winOrLose = QtWidgets.QLabel(self.centralwidget)
        self.winOrLose.setGeometry(QtCore.QRect(150, 240, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.winOrLose.setFont(font)
        self.winOrLose.setText("")
        self.winOrLose.setObjectName("winOrLose")
        self.continueButton = QtWidgets.QPushButton(self.centralwidget)
        self.continueButton.setGeometry(QtCore.QRect(210, 360, 91, 31))
        self.continueButton.setVisible(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.continueButton.setFont(font)
        self.continueButton.setObjectName("continueButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setDefaultUp(True)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionRules = QtWidgets.QAction(MainWindow)
        self.actionRules.setObjectName("actionRules")
        self.actionChange = QtWidgets.QAction(MainWindow)
        self.actionChange.setObjectName("actionChange")
        self.menuFile.addAction(self.actionClose)
        self.menuSettings.addAction(self.actionChange)
        self.menuHelp.addAction(self.actionRules)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.retranslateUi(MainWindow)
        self.actionClose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Новая игра"))
        self.strScore.setText(_translate("MainWindow", "Счет"))
        self.strTheBestScore.setText(_translate("MainWindow", "Лучший"))
        self.valueTheBestScore.setText(_translate("MainWindow", "0"))
        self.str2048.setText(_translate("MainWindow", "2048"))
        self.valueScore.setText(_translate("MainWindow", "0"))
        self.continueButton.setText(_translate("MainWindow", "Продолжить"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuSettings.setTitle(_translate("MainWindow", "Настройки"))
        self.menuHelp.setTitle(_translate("MainWindow", "Помощь"))
        self.actionClose.setText(_translate("MainWindow", "Закрыть"))
        self.action.setText(_translate("MainWindow", "Правила"))
        self.actionRules.setText(_translate("MainWindow", "Правила"))
        self.actionChange.setText(_translate("MainWindow", "Изменить"))

